-- begin GCSPLATFORM_AGENT
alter table GCSPLATFORM_AGENT add constraint FK_GCSPLATFORM_AGENT_ON_COUNTERPARTY foreign key (COUNTERPARTY_ID) references GCSPLATFORM_COUNTERPARTY(ID)^
create index IDX_GCSPLATFORM_AGENT_ON_COUNTERPARTY on GCSPLATFORM_AGENT (COUNTERPARTY_ID)^
-- end GCSPLATFORM_AGENT
-- begin GCSPLATFORM_DEALER
alter table GCSPLATFORM_DEALER add constraint FK_GCSPLATFORM_DEALER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_GCSPLATFORM_DEALER_ON_USER on GCSPLATFORM_DEALER (USER_ID)^
-- end GCSPLATFORM_DEALER
