create table GCSPLATFORM_LIVE_TRADE (
    ID varchar(32),
    VERSION integer not null,
    CREATE_TS datetime(3),
    CREATED_BY varchar(50),
    UPDATE_TS datetime(3),
    UPDATED_BY varchar(50),
    DELETE_TS datetime(3),
    DELETED_BY varchar(50),
    --
    BOND_DESCRIPTION varchar(50),
    BROOVERIDE boolean,
    BUYBROKER varchar(10),
    BUYBROKERAGE decimal(10, 4),
    BUYER varchar(30),
    BUYER_AGENT varchar(30),
    CALLOPTION varchar(20),
    CATEGORY varchar(10),
    CPAIR1 varchar(10),
    CPAIR2 varchar(10),
    CPAIR3 varchar(10),
    CURRENCY varchar(5),
    GBP_EQUIVALENT decimal(10, 4),
    GC boolean,
    HAIR_CUT decimal(10, 4),
    ISIN varchar(20),
    MATURITY_DATE datetime(3),
    NOMINAL decimal(10, 2),
    NOTES varchar(100),
    NUMDAYS integer,
    ORIGTRADEREF varchar(20),
    REPO_RATE decimal(10, 4),
    SELLBROKER varchar(10),
    SELLBROKERAGE decimal(10, 4),
    SELLER varchar(30),
    SELLER_AGENT varchar(30),
    SPECIAL boolean,
    START_PRICE decimal(10, 4),
    STATUS varchar(10),
    SUBS boolean,
    TRADE_CURRENCY varchar(5),
    TRADE_DATE datetime(3),
    TRADEREF varchar(20),
    UTI varchar(50),
    VALUE_DATE datetime(3),
    XRATE1 decimal(10, 4),
    XRATE2 decimal(10, 4),
    XRATE3 decimal(10, 4),
    SUB_THIRTY boolean,
    MORE_THAN_THIRTY boolean,
    GM_SLA boolean,
    --
    primary key (ID)
);