alter table GCSPLATFORM_FX add constraint FK_GCSPLATFORM_FX_ON_CURRENCY foreign key (CURRENCY_ID) references GCSPLATFORM_CURRENCY(ID);
create unique index IDX_GCSPLATFORM_FX_UNQ on GCSPLATFORM_FX (CURRENCY_ID, BILLING_DATE) ;
create index IDX_GCSPLATFORM_FX_ON_CURRENCY on GCSPLATFORM_FX (CURRENCY_ID);
