update GCSPLATFORM_COUNTERPARTY_BROKERAGE set BROKERAGE_VALUE = 0 where BROKERAGE_VALUE is null ;
alter table GCSPLATFORM_COUNTERPARTY_BROKERAGE modify column BROKERAGE_VALUE decimal(10, 4) not null ;
