alter table GCSPLATFORM_AGENT add constraint FK_GCSPLATFORM_AGENT_ON_COUNTERPARTY foreign key (COUNTERPARTY_ID) references GCSPLATFORM_COUNTERPARTY(ID);
create index IDX_GCSPLATFORM_AGENT_ON_COUNTERPARTY on GCSPLATFORM_AGENT (COUNTERPARTY_ID);
