alter table GCSPLATFORM_DEALER add constraint FK_GCSPLATFORM_DEALER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_GCSPLATFORM_DEALER_ON_USER on GCSPLATFORM_DEALER (USER_ID);
