alter table GCSPLATFORM_INVOICE add constraint FK_GCSPLATFORM_INVOICE_ON_PDF_FILE foreign key (PDF_FILE_ID) references SYS_FILE(ID);
create index IDX_GCSPLATFORM_INVOICE_ON_PDF_FILE on GCSPLATFORM_INVOICE (PDF_FILE_ID);
