alter table GCSPLATFORM_LIVE_TRADE change column SELLER_INVOICE_CODE SELLER_INVOICE_CODE__U45483 varchar(50)^
alter table GCSPLATFORM_LIVE_TRADE change column BUYER_INVOICE_CODE BUYER_INVOICE_CODE__U11809 varchar(50)^
