alter table GCSPLATFORM_OPENED_TRADE change column BUYER_INVOICE_CODE BUYER_COUNTRY varchar(50);
alter table GCSPLATFORM_OPENED_TRADE change column SELLER_INVOICE_CODE SELLER_COUNTRY varchar(50);
update GCSPLATFORM_OPENED_TRADE t1, GCSPLATFORM_OPENED_TRADE t2 set t1.BUYER_LOCATION = t1.BUYER_COUNTRY, t2.BUYER_COUNTRY = t1.BUYER_LOCATION where t1.id = t2.id;
update GCSPLATFORM_OPENED_TRADE t1, GCSPLATFORM_OPENED_TRADE t2 set t1.SELLER_LOCATION = t1.SELLER_COUNTRY, t2.SELLER_COUNTRY = t1.SELLER_LOCATION where t1.id = t2.id;

alter table GCSPLATFORM_CLOSED_TRADE change column BUYER_INVOICE_CODE BUYER_COUNTRY varchar(50);
alter table GCSPLATFORM_CLOSED_TRADE change column SELLER_INVOICE_CODE SELLER_COUNTRY varchar(50);
update GCSPLATFORM_CLOSED_TRADE t1, GCSPLATFORM_CLOSED_TRADE t2 set t1.BUYER_LOCATION = t1.BUYER_COUNTRY, t2.BUYER_COUNTRY = t1.BUYER_LOCATION where t1.id = t2.id;
update GCSPLATFORM_CLOSED_TRADE t1, GCSPLATFORM_CLOSED_TRADE t2 set t1.SELLER_LOCATION = t1.SELLER_COUNTRY, t2.SELLER_COUNTRY = t1.SELLER_LOCATION where t1.id = t2.id;

alter table GCSPLATFORM_CLOSED_LIVE_TRADE change column BUYER_INVOICE_CODE BUYER_COUNTRY varchar(50);
alter table GCSPLATFORM_CLOSED_LIVE_TRADE change column SELLER_INVOICE_CODE SELLER_COUNTRY varchar(50);
update GCSPLATFORM_CLOSED_LIVE_TRADE set BUYER_LOCATION = BUYER_COUNTRY, BUYER_COUNTRY = BUYER_LOCATION;
update GCSPLATFORM_CLOSED_LIVE_TRADE set SELLER_LOCATION = SELLER_COUNTRY, SELLER_COUNTRY = SELLER_LOCATION;
update GCSPLATFORM_CLOSED_LIVE_TRADE t1, GCSPLATFORM_CLOSED_LIVE_TRADE t2 set t1.BUYER_LOCATION = t1.BUYER_COUNTRY, t2.BUYER_COUNTRY = t1.BUYER_LOCATION where t1.id = t2.id;
update GCSPLATFORM_CLOSED_LIVE_TRADE t1, GCSPLATFORM_CLOSED_LIVE_TRADE t2 set t1.SELLER_LOCATION = t1.SELLER_COUNTRY, t2.SELLER_COUNTRY = t1.SELLER_LOCATION where t1.id = t2.id;

alter table GCSPLATFORM_CALL_OPTION_TRADE change column BUYER_INVOICE_CODE BUYER_COUNTRY varchar(50);
alter table GCSPLATFORM_CALL_OPTION_TRADE change column SELLER_INVOICE_CODE SELLER_COUNTRY varchar(50);
update GCSPLATFORM_CALL_OPTION_TRADE t1, GCSPLATFORM_CALL_OPTION_TRADE t2 set t1.BUYER_LOCATION = t1.BUYER_COUNTRY, t2.BUYER_COUNTRY = t1.BUYER_LOCATION where t1.id = t2.id;
update GCSPLATFORM_CALL_OPTION_TRADE t1, GCSPLATFORM_CALL_OPTION_TRADE t2 set t1.SELLER_LOCATION = t1.SELLER_COUNTRY, t2.SELLER_COUNTRY = t1.SELLER_LOCATION where t1.id = t2.id;

alter table GCSPLATFORM_LIVE_TRADE change column BUYER_INVOICE_CODE BUYER_COUNTRY varchar(50);
alter table GCSPLATFORM_LIVE_TRADE change column SELLER_INVOICE_CODE SELLER_COUNTRY varchar(50);
update GCSPLATFORM_LIVE_TRADE t1, GCSPLATFORM_LIVE_TRADE t2 set t1.BUYER_LOCATION = t1.BUYER_COUNTRY, t2.BUYER_COUNTRY = t1.BUYER_LOCATION where t1.id = t2.id;
update GCSPLATFORM_LIVE_TRADE t1, GCSPLATFORM_LIVE_TRADE t2 set t1.SELLER_LOCATION = t1.SELLER_COUNTRY, t2.SELLER_COUNTRY = t1.SELLER_LOCATION where t1.id = t2.id;
