update GCSPLATFORM_COUNTERPARTY_BROKERAGE set BROKERAGE_TYPE = 'GEN' where BROKERAGE_TYPE = 'GC' ;
update GCSPLATFORM_COUNTERPARTY_BROKERAGE set BROKERAGE_TYPE = 'SPE' where BROKERAGE_TYPE = 'SPECIAL' ;
update GCSPLATFORM_COUNTERPARTY_BROKERAGE set BROKERAGE_TYPE = 'M30D' where BROKERAGE_TYPE = 'MORE_THAN_THIRTY' ;
update GCSPLATFORM_COUNTERPARTY_BROKERAGE set BROKERAGE_TYPE = 'S30D' where BROKERAGE_TYPE = 'SUB_THIRTY' ;
