update GCSPLATFORM_COUNTERPARTY set LOCATION_ID = '2f069ce385c542ffb582bcbb370f33b4' where LOCATION_ID <> 'LON' and LOCATION_ID <> 'HK';
update GCSPLATFORM_COUNTERPARTY set LOCATION_ID = '2f069ce385c542ffb582bcbb370f33b4' where LOCATION_ID = 'LON';
update GCSPLATFORM_COUNTERPARTY set LOCATION_ID = 'e0558c71389d439baf7aeef981a2951e' where LOCATION_ID = 'HK';


alter table GCSPLATFORM_COUNTERPARTY add constraint FK_GCSPLATFORM_COUNTERPARTY_ON_LOCATION foreign key (LOCATION_ID) references GCSPLATFORM_LOCATION(ID);
create index IDX_GCSPLATFORM_COUNTERPARTY_ON_LOCATION on GCSPLATFORM_COUNTERPARTY (LOCATION_ID);
