alter table GCSPLATFORM_INVOICE_LINE add constraint FK_GCSPLATFORM_INVOICE_LINE_ON_TRADE foreign key (TRADE_ID) references GCSPLATFORM_CLOSED_TRADE(ID);
create index IDX_GCSPLATFORM_INVOICE_LINE_ON_TRADE on GCSPLATFORM_INVOICE_LINE (TRADE_ID);
