alter table GCSPLATFORM_INVOICE_BANK add constraint FK_GCSPLATFORM_INVOICE_BANK_ON_CURRENCY foreign key (CURRENCY_ID) references GCSPLATFORM_CURRENCY(ID);
alter table GCSPLATFORM_INVOICE_BANK add constraint FK_GCSPLATFORM_INVOICE_BANK_ON_BANK foreign key (BANK_ID) references GCSPLATFORM_BANK(ID);
create unique index IDX_GCSPLATFORM_INVOICE_BANK_UNQ on GCSPLATFORM_INVOICE_BANK (CURRENCY_ID, LOCATION) ;
create index IDX_GCSPLATFORM_INVOICE_BANK_ON_CURRENCY on GCSPLATFORM_INVOICE_BANK (CURRENCY_ID);
create index IDX_GCSPLATFORM_INVOICE_BANK_ON_BANK on GCSPLATFORM_INVOICE_BANK (BANK_ID);
