alter table GCSPLATFORM_BROKER add constraint FK_GCSPLATFORM_BROKER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create unique index IDX_GCSPLATFORM_BROKER_UNIQ_NAME on GCSPLATFORM_BROKER (NAME) ;
create index IDX_GCSPLATFORM_BROKER_ON_USER on GCSPLATFORM_BROKER (USER_ID);
