alter table GCSPLATFORM_CLOSED_LIVE_TRADE add column BUY_PUT_ON_INVOICE boolean ;
alter table GCSPLATFORM_CLOSED_LIVE_TRADE add column SELL_COMISSION_OVERRIDE boolean ;
alter table GCSPLATFORM_CLOSED_LIVE_TRADE add column BUY_COMMISSION_OVERRIDE boolean ;
alter table GCSPLATFORM_CLOSED_LIVE_TRADE add column SELL_PUT_ON_INVOICE boolean ;
